# Generated by Django 4.1.3 on 2024-08-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_manager',
        ),
    ]
