version: '3.2'
services:

  portfolio-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: portfolio-backend
    networks:
      - default
      - proxy
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend/app:/app:rw

      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    entrypoint: /entrypoint.sh
    env_file:
      - ./backend/environments/prod.env
    command: gunicorn app.wsgi:application --bind 0.0.0.0:80
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
  
  portfolio-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    networks:
      - default
      - proxy
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frontend/app:/app:rw

      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      - staticfiles:/staticfiles:ro
      - mediafiles:/mediafiles:ro
    environment:
      - VIRTUAL_HOST=portfolio.horadrim.keenetic.link
      - LETSENCRYPT_HOST=portfolio.horadrim.keenetic.link
      - LETSENCRYPT_EMAIL=email.alexss@gmail.com
    depends_on:
      portfolio-backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  staticfiles:
  mediafiles:

networks:
  default:
    name: portfolio
  proxy:
    name: 'proxy'
    external: true
