version: '3.2'
services:

  paydocs-ecotec-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: paydocs-ecotec-backend
    networks:
      - default
      - proxy
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend/app:/app:rw
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - ./backend/environments/test-prod.env
    # ports:
    #   - 8003:80
    entrypoint: /entrypoint.sh
    command: gunicorn app.wsgi:application --bind 0.0.0.0:80
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
  
  paydocs-ecotec-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: paydocs-ecotec-frontend
    networks:
      - default
      - proxy
    working_dir: /app
    # ports:
    #   - "4200:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frontend/app:/app:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/staticfiles:ro
      - mediafiles:/mediafiles:ro
    environment:
      - VIRTUAL_HOST=paydocs.horadrim.keenetic.link
      - LETSENCRYPT_HOST=paydocs.horadrim.keenetic.link
      - LETSENCRYPT_EMAIL=email.alexss@gmail.com
    depends_on:
      paydocs-ecotec-backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  staticfiles:
  mediafiles:

networks:
  default:
    name: paydocs-ecotec
  proxy:
    name: 'proxy'
    external: true
