# Generated by Django 4.1.3 on 2024-08-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorMyski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Мыски)',
                'db_table': 'ls_myski',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DebtorKiselevsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Киселевск)',
                'db_table': 'ls_kiselevsk',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DebtorKrasnobrod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Краснобродский)',
                'db_table': 'ls_krasnobrod',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DebtorProkopyevsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Прокопьевск)',
                'db_table': 'ls_prk',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DebtProkopyevsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtorprokopyevsk', to_field='ls')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('opl', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Прокопьевск)',
                'db_table': 'kartdolg_prk',
            },
        ),
        migrations.CreateModel(
            name='DebtKrasnobrod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtorkrasnobrod', to_field='ls')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('opl', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Краснобродский)',
                'db_table': 'kartdolg_krasnobrod',
            },
        ),
        migrations.CreateModel(
            name='DebtKiselevsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtorkiselevsk', to_field='ls')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('opl', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Киселевск)',
                'db_table': 'kartdolg_kiselevsk',
            },
        ),
        migrations.CreateModel(
            name='DebtMyski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtormyski', to_field='ls')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('opl', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Мыски)',
                'db_table': 'kartdolg_myski',
            },
        ),
    ]
