# Generated by Django 4.1.3 on 2024-08-10 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorArtyshta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Артышта)',
                'db_table': 'ls_artyshta',
            },
        ),
        migrations.CreateModel(
            name='DebtorDubrovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Дуброво)',
                'db_table': 'ls_dubrovo',
            },
        ),
        migrations.CreateModel(
            name='DebtorKrasnobrod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Краснобродский)',
                'db_table': 'ls_krasnobrod',
            },
        ),
        migrations.CreateModel(
            name='DebtorProkopyevsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='KV')),
                ('ls', models.CharField(max_length=128, unique=True, verbose_name='Лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия имя отчество')),
                ('otk', models.CharField(blank=True, max_length=512, null=True, verbose_name='OTK')),
                ('zak', models.CharField(blank=True, max_length=512, null=True, verbose_name='ZAK')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('pr', models.CharField(blank=True, max_length=512, null=True, verbose_name='PR')),
            ],
            options={
                'verbose_name_plural': 'должники (Прокопьевск)',
                'db_table': 'ls_prk',
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='index')),
                ('gorod', models.CharField(blank=True, max_length=512, null=True, verbose_name='город')),
                ('rayon', models.CharField(blank=True, max_length=512, null=True, verbose_name='район')),
                ('ulica', models.CharField(blank=True, max_length=512, null=True, verbose_name='улица')),
                ('dom', models.CharField(blank=True, max_length=512, null=True, verbose_name='дом')),
                ('kv', models.CharField(blank=True, max_length=512, null=True, verbose_name='квартира')),
                ('pr', models.IntegerField(default=0, verbose_name='pr')),
                ('period', models.CharField(max_length=64, verbose_name='период')),
                ('ls', models.CharField(blank=True, max_length=512, verbose_name='лицевой счет')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='фамилия имя отчество')),
                ('opl_tko', models.FloatField(default=0, verbose_name='опл тко')),
                ('vh_saldo', models.FloatField(default=0, verbose_name='входящее сальдо')),
                ('nacis', models.FloatField(default=0, verbose_name='начисление')),
                ('kor', models.FloatField(default=0, verbose_name='корректировка')),
                ('opl', models.FloatField(default=0, verbose_name='опл')),
                ('ish_saldo', models.FloatField(default=0, verbose_name='исходящее сальдо')),
                ('vh_saldo_pen', models.FloatField(default=0, verbose_name='вх.с.пен')),
                ('pen', models.FloatField(default=0, verbose_name='пеня')),
                ('kor_pen', models.FloatField(default=0, verbose_name='кор.пен.')),
                ('opl_pen', models.FloatField(default=0, verbose_name='опл.пен.')),
                ('ish_saldo_pen', models.FloatField(default=0, verbose_name='исх.с.пен')),
                ('ad', models.CharField(blank=True, max_length=512, null=True, verbose_name='адрес')),
                ('active', models.CharField(max_length=512, verbose_name='активен')),
                ('tip', models.CharField(max_length=64, verbose_name='тип')),
                ('itog', models.FloatField(default=0, verbose_name='итого')),
                ('qr', models.CharField(blank=True, max_length=1024, verbose_name='qr')),
                ('uid', models.CharField(max_length=512, verbose_name='uid')),
                ('dolg_m', models.IntegerField(default=0, verbose_name='dolgm')),
                ('soob', models.CharField(blank=True, max_length=5096, verbose_name='soob')),
                ('vh_saldo_s', models.FloatField(default=0, verbose_name='входящее сальдо c.')),
                ('nacis_s', models.FloatField(default=0, verbose_name='начисление с.')),
                ('kor_s', models.FloatField(default=0, verbose_name='корректировка с.')),
                ('opl_s', models.FloatField(default=0, verbose_name='опл c.')),
                ('ish_saldo_s', models.FloatField(default=0, verbose_name='исходящее сальдо c.')),
                ('itog_vse', models.FloatField(default=0, verbose_name='итог все')),
                ('potok', models.IntegerField(default=0, verbose_name='potok')),
                ('nn', models.IntegerField(default=0, verbose_name='nn')),
                ('nns', models.IntegerField(default=0, verbose_name='nns')),
            ],
            options={
                'verbose_name': 'квиток',
                'verbose_name_plural': 'квитки',
                'db_table': 'kvitok',
            },
        ),
        migrations.CreateModel(
            name='DebtProkopyevsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, to='debts.debtorprokopyevsk', to_field='ls')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Прокопьевск)',
                'db_table': 'kartdolg_prk',
            },
        ),
        migrations.CreateModel(
            name='DebtKrasnobrod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, to='debts.debtorkrasnobrod', to_field='ls')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Краснобродский)',
                'db_table': 'kartdolg_krasnobrod',
            },
        ),
        migrations.CreateModel(
            name='DebtDubrovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, to='debts.debtordubrovo', to_field='ls')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Дуброво)',
                'db_table': 'kartdolg_dubrovo',
            },
        ),
        migrations.CreateModel(
            name='DebtArtyshta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('nacis', models.FloatField(blank=True, default=0, verbose_name='Начисление')),
                ('korekt', models.FloatField(blank=True, default=0, verbose_name='Korekt')),
                ('pen', models.FloatField(blank=True, default=0, verbose_name='Пеня')),
                ('dolgsud', models.FloatField(blank=True, default=0, verbose_name='Судебный долг')),
                ('sitog', models.FloatField(blank=True, default=0, verbose_name='Сумма итого')),
                ('ls', models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, to='debts.debtorartyshta', to_field='ls')),
            ],
            options={
                'verbose_name_plural': 'задолженности (Артышта)',
                'db_table': 'kartdolg_artyshta',
            },
        ),
    ]
