# Generated by Django 4.1.3 on 2024-08-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtartyshta',
            name='ls',
            field=models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtorartyshta', to_field='ls'),
        ),
        migrations.AlterField(
            model_name='debtdubrovo',
            name='ls',
            field=models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtordubrovo', to_field='ls'),
        ),
        migrations.AlterField(
            model_name='debtkrasnobrod',
            name='ls',
            field=models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtorkrasnobrod', to_field='ls'),
        ),
        migrations.AlterField(
            model_name='debtprokopyevsk',
            name='ls',
            field=models.ForeignKey(db_column='ls', on_delete=django.db.models.deletion.CASCADE, related_name='debt_set', to='debts.debtorprokopyevsk', to_field='ls'),
        ),
    ]
