# Generated by Django 4.1.3 on 2024-08-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_debtartyshta_ls_alter_debtdubrovo_ls_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDocument',
        ),
    ]
