# Generated by Django 4.1.3 on 2024-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_delete_paymentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtartyshta',
            name='opl',
            field=models.FloatField(blank=True, default=0, verbose_name='Судебный долг'),
        ),
        migrations.AddField(
            model_name='debtdubrovo',
            name='opl',
            field=models.FloatField(blank=True, default=0, verbose_name='Судебный долг'),
        ),
        migrations.AddField(
            model_name='debtkrasnobrod',
            name='opl',
            field=models.FloatField(blank=True, default=0, verbose_name='Судебный долг'),
        ),
        migrations.AddField(
            model_name='debtprokopyevsk',
            name='opl',
            field=models.FloatField(blank=True, default=0, verbose_name='Судебный долг'),
        ),
    ]
