# Generated by Django 4.1.3 on 2024-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debtartyshta_opl_debtdubrovo_opl_debtkrasnobrod_opl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtorartyshta',
            options={'ordering': ['id'], 'verbose_name_plural': 'должники (Артышта)'},
        ),
        migrations.AlterModelOptions(
            name='debtordubrovo',
            options={'ordering': ['id'], 'verbose_name_plural': 'должники (Дуброво)'},
        ),
        migrations.AlterModelOptions(
            name='debtorkrasnobrod',
            options={'ordering': ['id'], 'verbose_name_plural': 'должники (Краснобродский)'},
        ),
        migrations.AlterModelOptions(
            name='debtorprokopyevsk',
            options={'ordering': ['id'], 'verbose_name_plural': 'должники (Прокопьевск)'},
        ),
    ]
