# Generated by Django 4.1.3 on 2024-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paydocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdocument',
            options={'ordering': ['id'], 'verbose_name': 'платежный документ', 'verbose_name_plural': 'платежные документы'},
        ),
    ]
