# Generated by Django 4.1.3 on 2024-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paydocs', '0002_alter_paymentdocument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_tko', models.FloatField(blank=True, null=True, verbose_name='Тариф ТКО')),
                ('contacts_html', models.TextField(blank=True, null=True, verbose_name='Блок с контактами')),
                ('details_html', models.TextField(blank=True, null=True, verbose_name='Блок с реквизитами')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Блок с примечанием')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
