# Generated by Django 4.1.3 on 2024-08-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paydocs', '0003_paymentdocumentsettings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentdocumentsettings',
            table='kvitok_settings',
        ),
    ]
