# Generated by Django 4.1.3 on 2024-08-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paydocs', '0004_alter_paymentdocumentsettings_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdocumentsettings',
            old_name='annotation',
            new_name='annotation_html',
        ),
    ]
